---
title: "20250819_raw_processing_gap_checker"
author: "Elspeth Sage"
date: "2025-08-19"
output:
  html_document: default
  pdf_document: default
---

```{r (1) setup, include=FALSE }
# Setting paths for working directory, retrieving data and saving figures and outputs - CHANGE TO SUIT YOU
setwd("C:/Users/ElspethSage/OneDrive - THE ROYAL SOCIETY FOR THE PROTECTION OF BIRDS/Documents/BRAIDS/WORKING")
scriptpath <- "C:/Users/ElspethSage/OneDrive - THE ROYAL SOCIETY FOR THE PROTECTION OF BIRDS/Documents/BRAIDS/WORKING/Scripts/Preprocessing/"
datpath <- "C:/Users/ElspethSage/OneDrive - THE ROYAL SOCIETY FOR THE PROTECTION OF BIRDS/Documents/BRAIDS/WORKING/Data/Tracks_processed/Kittiwake/"

# Savepath for where you want processed tracks to live
savepath <- "C:/Users/ElspethSage/OneDrive - THE ROYAL SOCIETY FOR THE PROTECTION OF BIRDS/Documents/BRAIDS/WORKING/Outputs/Preprocessing_outputs"

```

```{r (2) libraries, warning = FALSE, message = FALSE}
library(lubridate)
library(dplyr)
library(sp)
library(sf)
library(purrr)
library(ggplot2)
library(cowplot)
```

```{r read in data}
GPS <- read.csv(paste(datpath, 'SAH_2025_KITTI_Tracks.csv', sep = ''), header = TRUE, sep = ",", stringsAsFactors=FALSE, row.names = NULL)

```

```{r create date_times and intervals}
GPS$date_time <- as_datetime(paste(GPS$Year, '/' ,GPS$Month, '/', GPS$Day, '/', GPS$Hour, ':', GPS$Minute, ':', GPS$Second))

GPS_out <- c()
for(i in 1:length(unique(GPS$Tag_ID))){
  GPS_i <- subset(GPS, Tag_ID %in% unique(GPS$Tag_ID)[i])
  GPS_i <- GPS_i[order(GPS_i$date_time),]
  GPS_i$timeinterval_f <- c(NA,difftime(GPS_i$date_time[-1], GPS_i$date_time[-length(GPS_i$date_time)], units = "secs"))
  
  GPS_out <- rbind(GPS_out, GPS_i)
}

GPS <- GPS_out 
```

```{r interrogate time gaps}
GPSsumm <- GPS %>% group_by(Tag_ID) %>% summarise(nfixes = length(date_time), 
                                                  start_time = min(date_time), 
                                                  end_time = max(date_time), 
                                                  minInterval = min(timeinterval_f, na.rm = TRUE), maxInterval = max(timeinterval_f, na.rm = TRUE), medianInterval = median(timeinterval_f, na.rm = TRUE))

```

```{r plot some time gaps?}
# Create directories for outputs if not already existing

for(i in 1:length(unique(GPS$Tag_ID))){

  temp <- subset(GPS, Tag_ID == unique(GPS$Tag_ID)[i])
p1 <- ggplot(temp, aes(x = date_time, y = Battery))+
  geom_line(color = 'red')+
  ylim(3.6,4.25)
p2 <- ggplot(temp, aes(x = date_time, y = timeinterval_f))+
  geom_point(color = 'blue')

p <- plot_grid(p1, p2, labels = c('A', 'B'), label_size = 12)

    title <- paste(savepath,'/Figures/battery_timegaps_2025/SAH_', date(temp$date_time[1]),'_', date(temp$date_time[nrow(temp)]),'_logger_', unique(GPS$Tag_ID)[i], '.png', sep = '') 
    # ggsave(title,plot = p,width = 15, height = 6, dpi = 150, units = "in", device='png')

    print(p)
}
                       
```
